# Generated by Django 5.0.2 on 2024-02-09 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookreview', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='body',
            field=models.TextField(blank=True, max_length=8192),
        ),
    ]
