# Generated by Django 5.0.2 on 2024-02-14 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookreview", "0003_alter_review_body_alter_review_headline_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="rating",
            field=models.CharField(max_length=128, verbose_name="Titre2"),
        ),
    ]
